name: CI

on:
  push:
    branches:
    - main
    tags:
    - "v*"

jobs:
  platformio-build:
    runs-on: ubuntu-latest
    container: infinitecoding/platformio-for-ci:5.0.4

    steps:
      - uses: actions/checkout@v2

      - name: Prepare config
        run: cp include/config.h-example include/config.h

      - name: Build firmware
        run: platformio run -d .

      - name: Upload firware artifact
        uses: actions/upload-artifact@v2
        with:
          name: firmware.elf
          path: .pio/build/d1_mini_lite/firmware.elf
        if: ${{ github.ref == 'ref/head/v*' }}
